TravisCI now with custom per-OS release deployment for GitHub, via REST API.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -6,11 +6,12 @@ branches:
   only:
     - develop
   except:
-    - '/^untagged-/'
-    - '/-preview$/'
-    - '/^(?i:deploy)-.*$/'
-    - '/^v\\d+\\.\\d+\\.\\d+/'
-    - /^(?i:continuous)$/
+    - '/^.*-?(?i:latest)-?.*$/'
+    - '/^.*-?(?i:untagged)-?.*$/'
+    - '/^.*-?(?i:preview)-?.*$/'
+    - '/^.*-?(?i:deploy)-?.*$/'
+    - '/^v\\d+\\.\\d+\\.\\d+.*$/'
+    - /^.*-?(?i:continuous)-?.*$/
 matrix:
   include:
     - os: osx
@@ -21,6 +22,12 @@ matrix:
         - ELECTRON_CACHE=$HOME/.cache/electron
         - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
     - os: linux
+      language: node_js
+      node_js: "10"
+      env:
+        - ELECTRON_CACHE=$HOME/.cache/electron
+        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
+    - os: windows
       language: node_js
       node_js: "10"
       env:
@@ -52,8 +59,6 @@ script:
     fi'
 
 after_success:
-  - 'npm --version'
-  - 'node --version'
   - 'pwd'
   - 'ls -als'
   - 'ls -als dist'
@@ -63,8 +68,6 @@ after_success:
   - 'ls -als electron-pack/linux-unpacked'
   - 'ls -als electron-pack/win-unpacked'
 after_failure:
-  - 'npm --version'
-  - 'node --version'
   - 'pwd'
   - 'ls -als'
   - 'ls -als dist'
@@ -75,23 +78,25 @@ after_failure:
   - 'ls -als electron-pack/win-unpacked'
 # https://docs.travis-ci.com/user/deployment/
 before_deploy:
-  - git config --local user.name "danielweck"
-  - git config --local user.email "daniel.weck@gmail.com"
-  - git tag -l --format="%(refname)   %(taggerdate)"
-  - echo $TRAVIS_BRANCH
-  - export GIT_COMMITTER_DATE="$(git show $TRAVIS_BRANCH --format=%aD | head -1)" && echo $GIT_COMMITTER_DATE
-  - export GIT_TAG_CURRENT=$(git describe --abbrev=0 --tags) && echo $GIT_TAG_CURRENT
-  - 'if [[ $GIT_TAG_CURRENT == *-preview ]] ; then
-    export TRAVIS_TAG=$GIT_TAG_CURRENT && echo $TRAVIS_TAG ;
-    else
-    export GIT_TAG_CURRENT_NUM=${GIT_TAG_CURRENT:1} && echo $GIT_TAG_CURRENT_NUM &&
-    export GIT_TAG_CURRENT_NUM_LAST_DIGIT=${GIT_TAG_CURRENT_NUM:4} && echo $GIT_TAG_CURRENT_NUM_LAST_DIGIT &&
-    export GIT_TAG_CURRENT_NUM_LAST_DIGIT_INC=$((GIT_TAG_CURRENT_NUM_LAST_DIGIT+1)) && echo $GIT_TAG_CURRENT_NUM_LAST_DIGIT_INC &&
-    export GIT_TAG_CURRENT_NUM_PREFIX=${GIT_TAG_CURRENT_NUM%.*} && echo $GIT_TAG_CURRENT_NUM_PREFIX &&
-    export TRAVIS_TAG="v${GIT_TAG_CURRENT_NUM_PREFIX}.${GIT_TAG_CURRENT_NUM_LAST_DIGIT_INC}-preview" && echo $TRAVIS_TAG &&
-    (git tag -a "${TRAVIS_TAG}" $TRAVIS_BRANCH -m "tag ${TRAVIS_TAG}" && echo "tag ok") || echo "tag fail (already exist?)" ;
-    fi'
-  - git tag -l --format="%(refname)   %(taggerdate)"
+  - export TRAVIS_TAG="latest-$TRAVIS_OS_NAME"
+  - node tools/release-github.js
+# - git config --local user.name "danielweck"
+# - git config --local user.email "daniel.weck@gmail.com"
+# - git tag -l --format="%(refname)   %(taggerdate)"
+# - echo $TRAVIS_BRANCH
+# - export GIT_COMMITTER_DATE="$(git show $TRAVIS_BRANCH --format=%aD | head -1)" && echo $GIT_COMMITTER_DATE
+# - export GIT_TAG_CURRENT=$(git describe --abbrev=0 --tags) && echo $GIT_TAG_CURRENT
+# - 'if [[ $GIT_TAG_CURRENT == *-preview ]] ; then
+#   export TRAVIS_TAG=$GIT_TAG_CURRENT && echo $TRAVIS_TAG ;
+#   else
+#   export GIT_TAG_CURRENT_NUM=${GIT_TAG_CURRENT:1} && echo $GIT_TAG_CURRENT_NUM &&
+#   export GIT_TAG_CURRENT_NUM_LAST_DIGIT=${GIT_TAG_CURRENT_NUM:4} && echo $GIT_TAG_CURRENT_NUM_LAST_DIGIT &&
+#   export GIT_TAG_CURRENT_NUM_LAST_DIGIT_INC=$((GIT_TAG_CURRENT_NUM_LAST_DIGIT+1)) && echo $GIT_TAG_CURRENT_NUM_LAST_DIGIT_INC &&
+#   export GIT_TAG_CURRENT_NUM_PREFIX=${GIT_TAG_CURRENT_NUM%.*} && echo $GIT_TAG_CURRENT_NUM_PREFIX &&
+#   export TRAVIS_TAG="v${GIT_TAG_CURRENT_NUM_PREFIX}.${GIT_TAG_CURRENT_NUM_LAST_DIGIT_INC}-preview" && echo $TRAVIS_TAG &&
+#   (git tag -a "${TRAVIS_TAG}" $TRAVIS_BRANCH -m "tag ${TRAVIS_TAG}" && echo "tag ok") || echo "tag fail (already exist?)" ;
+#   fi'
+# - git tag -l --format="%(refname)   %(taggerdate)"
 # ((curl -X DELETE --header "Authorization: token ${GH_TOKEN}" "https://api.github.com/repos/${TRAVIS_REPO_SLUG}/releases/${GIT_TAG_CURRENT}" && echo "delete release ok") || echo "delete release fail?") &&
 #  git tag -d $GIT_TAG_CURRENT &&
 #  git tag -l --format="%(refname)   %(taggerdate)" &&
@@ -111,7 +116,7 @@ deploy:
     - "electron-pack/**/*.dmg"
     - "!electron-pack/**/elevate*"
   skip_cleanup: true
-  name: "Continuous build (pre-release)"
+  name: "$TRAVIS_TAG continuous test build (pre-release)"
   prerelease: true
   on:
     branch: develop
